name: Deployment pipeline

on:
  push:
    branches:
      - github-action

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies 
        working-directory: ./myFitnessTrainer
        run: npm install  
      - name: Check style
        working-directory: ./myFitnessTrainer
        run: npm run eslint